# Generated by Django 4.0.6 on 2022-07-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_password_signup_pass1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='pass1',
            new_name='password',
        ),
    ]
