# Generated by Django 4.0.6 on 2022-07-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_name_signup_username_alter_signup_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('mobno', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('addtype', models.CharField(max_length=10)),
                ('idtype', models.CharField(max_length=10)),
                ('idno', models.IntegerField()),
                ('job', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
