# Generated by Django 4.0.6 on 2022-07-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='Detail',
        ),
    ]
