# Generated by Django 4.0.6 on 2022-08-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_details_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describeu', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('qualification', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=20)),
                ('professionalexp', models.CharField(max_length=20)),
                ('mothertongue', models.CharField(max_length=20)),
                ('describeurfamily', models.CharField(max_length=100)),
                ('familytype', models.CharField(max_length=100)),
                ('familyvalue', models.CharField(max_length=100)),
                ('familystatus', models.CharField(max_length=100)),
                ('maritalstatus', models.CharField(max_length=100)),
                ('hobbiesandinterest', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
    ]
