# Generated by Django 4.0.6 on 2022-08-02 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_detail1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail1',
            new_name='Detaila',
        ),
    ]
