# Generated by Django 4.0.6 on 2022-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_detail1_detaila'),
    ]

    operations = [
        migrations.AddField(
            model_name='detaila',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
