# Generated by Django 4.0.6 on 2022-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_preference1_preference2_delete_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('personallyf', models.CharField(max_length=20)),
                ('adoptchild', models.CharField(max_length=20)),
                ('lifewithdiv', models.CharField(max_length=20)),
                ('ambitious', models.CharField(max_length=20)),
                ('superstitious', models.CharField(max_length=20)),
                ('socialcom', models.CharField(max_length=20)),
                ('partnertalent', models.CharField(max_length=20)),
                ('partnerindep', models.CharField(max_length=20)),
                ('drinkorsmoke', models.CharField(max_length=20)),
                ('hangout', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Preference1',
        ),
        migrations.DeleteModel(
            name='Preference2',
        ),
    ]
