# Generated by Django 4.0.6 on 2022-08-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_preference_delete_preference1_delete_preference2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('socialcom', models.CharField(max_length=20)),
                ('partnertalent', models.CharField(max_length=20)),
                ('partnerindep', models.CharField(max_length=20)),
                ('drinkorsmoke', models.CharField(max_length=20)),
                ('hangout', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='Preference',
            new_name='Preference1',
        ),
    ]
