# Generated by Django 4.0.6 on 2022-08-03 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_preference2_rename_preference_preference1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference1',
            name='drinkorsmoke',
        ),
        migrations.RemoveField(
            model_name='preference1',
            name='hangout',
        ),
        migrations.RemoveField(
            model_name='preference1',
            name='partnerindep',
        ),
        migrations.RemoveField(
            model_name='preference1',
            name='partnertalent',
        ),
        migrations.RemoveField(
            model_name='preference1',
            name='socialcom',
        ),
    ]
