# Generated by Django 4.0.6 on 2022-09-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_preference1_drinkorsmoke_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phno', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
    ]
