# Generated by Django 4.0.6 on 2022-09-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
    ]
