# Generated by Django 4.0.6 on 2022-09-27 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_blog_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='name',
            new_name='username',
        ),
    ]
