# Generated by Django 4.0.6 on 2022-09-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_name_blogs_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phno', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
