# Generated by Django 4.0.6 on 2022-09-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='DEFAULT VALUE', max_length=20),
        ),
    ]
