# Generated by Django 4.0.6 on 2023-01-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_post_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('insta', models.CharField(max_length=100)),
                ('fb', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
            ],
        ),
    ]
