# Generated by Django 4.0.6 on 2023-02-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='insta',
            new_name='instagram',
        ),
    ]
