# Generated by Django 4.0.6 on 2023-02-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_instagram_social_insta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
