# Generated by Django 4.0.6 on 2023-02-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_social_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='insta',
            new_name='instagram',
        ),
    ]
